"use client"

import React from 'react'
import { 
  Plus, 
  LayoutDashboard, 
  Folder, 
  FileText, 
  Settings, 
  LogOut, 
  Search, 
  ArrowUpRight,
  Clock,
  CheckCircle2,
  Sparkles
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"

export default function DashboardPage() {
  return (
    <main className="flex-1 max-h-svh flex flex-col overflow-auto">
        {/* Header */}
        <header className="h-16 border-b border-border flex items-center justify-between px-8 bg-white/50 backdrop-blur-sm">
        <div className="relative w-96">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground size-4" />
            <Input placeholder="Search projects or artifacts..." className="pl-10 bg-muted/50 border-none h-10" />
        </div>
        <div className="flex items-center gap-4">
            <Button className="brand-bg hover:opacity-90 text-white gap-2">
                <Plus size={18} />
                New Project
            </Button>
            <div className="size-9 rounded-full brand-gradient flex items-center justify-center text-white font-bold text-sm">
            JD
            </div>
        </div>
        </header>

        {/* Scrollable Area */}
        <div className="flex-1 overflow-y-auto p-8 space-y-8">
        {/* Welcome Section */}
        <div className="flex justify-between items-end">
            <div>
            <h1 className="text-3xl font-bold tracking-tight">Welcome back, John!</h1>
            <p className="text-muted-foreground">You have 3 active sprints this week.</p>
            </div>
            <div className="hidden lg:block w-48 h-24">
            <img src="/dashboard-summary.svg" />
            </div>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <StatCard label="Total Artifacts" value="24" trend="+12% from last week" />
            <StatCard label="Active Projects" value="4" trend="2 Due this week" />
            <StatCard label="AI Efficiency" value="92%" trend="Time saved vs manual" />
        </div>

        {/* Project List */}
        <section className="space-y-4">
            <div className="flex items-center justify-between">
            <h2 className="text-xl font-semibold">Recent Projects</h2>
            <Button variant="link" className="brand-text">View all</Button>
            </div>
            
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
            <ProjectCard 
                title="E-Commerce Redesign" 
                sprint="Sprint 04" 
                progress={65} 
                artifacts={12} 
                status="Active"
            />
            <ProjectCard 
                title="Internal CRM Dashboard" 
                sprint="Sprint 01" 
                progress={15} 
                artifacts={3} 
                status="Planning"
            />
            </div>
        </section>

        {/* Recent Activity (Glass effect) */}
        <Card className="glass border-none">
            <CardHeader>
            <CardTitle className="text-lg">Recent AI Activity</CardTitle>
            <CardDescription>Latest artifacts generated by Gemini</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
            <ActivityItem icon={<CheckCircle2 className="text-green-500" />} text="User Stories for 'User Authentication' generated" time="2 mins ago" />
            <ActivityItem icon={<Clock className="brand-text" />} text="Sprint Backlog for 'Project Delta' updated" time="1 hour ago" />
            </CardContent>
        </Card>
        </div>
    </main>
  )
}

// --- Helper Components ---


function StatCard({ label, value, trend }: { label: string, value: string, trend: string }) {
  return (
    <Card className="border-border shadow-sm">
      <CardContent className="p-6">
        <p className="text-sm font-medium text-muted-foreground">{label}</p>
        <h3 className="text-3xl font-bold mt-1">{value}</h3>
        <p className="text-xs text-blue-600 mt-1 font-medium">{trend}</p>
      </CardContent>
    </Card>
  )
}

function ProjectCard({ title, sprint, progress, artifacts, status }: any) {
  return (
    <Card className="hover:border-blue-300 transition-all cursor-pointer group">
      <CardHeader className="flex flex-row items-center justify-between pb-2">
        <div>
          <CardTitle className="text-lg group-hover:brand-text transition-colors">{title}</CardTitle>
          <CardDescription>{sprint}</CardDescription>
        </div>
        <Badge variant={status === "Active" ? "default" : "secondary"} className={status === "Active" ? "brand-bg" : ""}>
          {status}
        </Badge>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex items-center justify-between text-sm">
          <span className="flex items-center gap-1 text-muted-foreground">
            <FileText size={14} /> {artifacts} Artifacts
          </span>
          <span className="font-semibold">{progress}%</span>
        </div>
        <div className="w-full bg-muted rounded-full h-2">
          <div className="brand-bg h-2 rounded-full" style={{ width: `${progress}%` }} />
        </div>
      </CardContent>
    </Card>
  )
}

function ActivityItem({ icon, text, time }: any) {
  return (
    <div className="flex items-center justify-between p-3 rounded-lg hover:bg-muted/50 transition-colors">
      <div className="flex items-center gap-3">
        {icon}
        <span className="text-sm font-medium">{text}</span>
      </div>
      <span className="text-xs text-muted-foreground">{time}</span>
    </div>
  )
}